version: 2.1
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:latest
    steps:
      - checkout
      - run: go mod download
      - run: golangci-lint run -v
  test:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: go mod download
      - run: go test -v -timeout 60s -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  build:
    jobs:
      - lint
      - test
